In [3]:
import os
import sys

import pandas as pd
import numpy as np
import matplotlib as plt
import torch
from PIL import Image
import torchvision
from torchvision import transforms

ModuleNotFoundError: No module named 'torchvision'

In [ ]:
print('Pandas version:', pd.__version__)
print('Numpy version:', np.__version__)
print('Matplotlib version:', plt.__version__)
print('Torch version:', torch.__version__)
print('Torchvision version:', torchvision.__version__)


Pandas version: 2.2.3
Numpy version: 2.2.1
Matplotlib version: 3.10.0
Torch version: 2.6.0+cpu
Torchvision version: 0.21.0+cpu


In [ ]:
mylist = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
myTensor = torch.Tensor(mylist)

print(myTensor)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]])


In [ ]:
# checkin the dimensional and the sixe of the tensor
print(myTensor.ndimension())    
print(myTensor.shape)
print(myTensor.dtype)

2
torch.Size([3, 5])
torch.float32


In [ ]:
myTensor.device

device(type='cpu')

In [ ]:
fgpus = torch.cuda.is_available()

mps_gpus = torch.backends.mps.is_available()

print(fgpus)
print(mps_gpus)

False
False


In [ ]:
# slicing the tensor
leftTensor = myTensor[:2, :]
rightTensor = myTensor[1:, :]

print(leftTensor)
print(rightTensor)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
tensor([[ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]])


In [ ]:
# Performing element wise multiplication and addition
ew_mulTensor = leftTensor * rightTensor
ew_addTensor = leftTensor + rightTensor

# using the in-built functions
mulTensor = leftTensor.mul(rightTensor)
addTensor = leftTensor.add(rightTensor)

print(ew_mulTensor)
print(ew_addTensor)
print(mulTensor)
print(addTensor)

tensor([[  6.,  14.,  24.,  36.,  50.],
        [ 66.,  84., 104., 126., 150.]])
tensor([[ 7.,  9., 11., 13., 15.],
        [17., 19., 21., 23., 25.]])
tensor([[  6.,  14.,  24.,  36.,  50.],
        [ 66.,  84., 104., 126., 150.]])
tensor([[ 7.,  9., 11., 13., 15.],
        [17., 19., 21., 23., 25.]])


In [ ]:
newLleftTensor = torch.Tensor([[1, 2], [6, 7]])
newRightTensor = torch.Tensor([[11],[16]])

print(newLleftTensor.shape)
print(newRightTensor.shape)

# matrix multiplication
matmulTensor = newLleftTensor.matmul(newRightTensor)
print(matmulTensor)

torch.Size([2, 2])
torch.Size([2, 1])
tensor([[ 43.],
        [178.]])


In [ ]:
myTensor.mean()
print(newLleftTensor.mean())
print(newLleftTensor.mean().shape)

tensor(4.)
torch.Size([])
