In [1]:
import os
import sys
import pandas as pd
import numpy as np
import matplotlib as plt
import torch
from PIL import Image
import torchvision
from torchvision import transforms

In [ ]:
print('Pandas version:', pd.__version__)
print('Numpy version:', np.__version__)
print('Matplotlib version:', plt.__version__)
print('Torch version:', torch.__version__)
print('Torchvision version:', torchvision.__version__)


Pandas version: 2.2.3
Numpy version: 2.2.1
Matplotlib version: 3.10.0
Torch version: 2.6.0+cpu
Torchvision version: 0.21.0+cpu


In [2]:
mylist = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
myTensor = torch.Tensor(mylist)

print(myTensor)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]])


In [3]:
# checkin the dimensional and the sixe of the tensor
print(myTensor.ndimension())
print(myTensor.shape)
print(myTensor.dtype)

2
torch.Size([3, 5])
torch.float32


In [4]:
myTensor.device

device(type='cpu')

In [5]:
fgpus = torch.cuda.is_available()

mps_gpus = torch.backends.mps.is_available()

print(fgpus)
print(mps_gpus)

False
False


In [6]:
# slicing the tensor
leftTensor = myTensor[:2, :]
rightTensor = myTensor[1:, :]

print(leftTensor)
print(rightTensor)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
tensor([[ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]])


In [7]:
# Performing element wise multiplication and addition
ew_mulTensor = leftTensor * rightTensor
ew_addTensor = leftTensor + rightTensor

# using the in-built functions
mulTensor = leftTensor.mul(rightTensor)
addTensor = leftTensor.add(rightTensor)

print(ew_mulTensor)
print(ew_addTensor)
print(mulTensor)
print(addTensor)

tensor([[  6.,  14.,  24.,  36.,  50.],
        [ 66.,  84., 104., 126., 150.]])
tensor([[ 7.,  9., 11., 13., 15.],
        [17., 19., 21., 23., 25.]])
tensor([[  6.,  14.,  24.,  36.,  50.],
        [ 66.,  84., 104., 126., 150.]])
tensor([[ 7.,  9., 11., 13., 15.],
        [17., 19., 21., 23., 25.]])


In [8]:
newLleftTensor = torch.Tensor([[1, 2], [6, 7]])
newRightTensor = torch.Tensor([[11],[16]])

print(newLleftTensor.shape)
print(newRightTensor.shape)

# matrix multiplication
matmulTensor = newLleftTensor.matmul(newRightTensor)
print(matmulTensor)

torch.Size([2, 2])
torch.Size([2, 1])
tensor([[ 43.],
        [178.]])


In [9]:
myTensor.mean()
print(newLleftTensor.mean())
print(newLleftTensor.mean().shape)

tensor(4.)
torch.Size([])


In [27]:
torch.manual_seed(42)

linear= torch.nn.Linear(in_features=5,out_features=3)
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[ 0.3419,  0.3712, -0.1048,  0.4108, -0.0980],
        [ 0.0902, -0.2177,  0.2626,  0.3942, -0.3281],
        [ 0.3887,  0.0837,  0.3304,  0.0606,  0.2156]], requires_grad=True)
Parameter containing:
tensor([-0.0631,  0.3448,  0.0661], requires_grad=True)


In [28]:
input = myTensor
input

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]])

In [29]:
output = linear(input)
output

tensor([[ 1.8602,  0.7240,  2.9339],
        [ 6.4660,  1.7305,  8.3291],
        [11.0718,  2.7370, 13.7242]], grad_fn=<AddmmBackward0>)

In [30]:
print(input.shape), print(output.shape)

torch.Size([3, 5])
torch.Size([3, 3])


(None, None)

In [31]:
# aggegation
print(output.argmax())
print(input.argmin())

tensor(8)
tensor(0)


In [32]:
output.max()

tensor(13.7242, grad_fn=<MaxBackward1>)

In [38]:
torch.reshape(input, (1, -1))

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15.]])

In [45]:
input.view((5,3))

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.]])